### ISSUE TITLE
Use validate_legacy

### ISSUE THREAD

**Issue by pmuller** [treydock/puppet-yum_cron#11]
``validate_*`` functions has been deprecated since stdlib 4.13.0:
```
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/yum_cron/manifests/init.pp", 34]:["/etc/puppetlabs/code/environments/production/site/profiles/manifests/base.pp", 7]
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/yum_cron/manifests/init.pp", 39]:["/etc/puppetlabs/code/environments/production/site/profiles/manifests/base.pp", 7]
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/yum_cron/manifests/init.pp", 48]:["/etc/puppetlabs/code/environments/production/site/profiles/manifests/base.pp", 7]
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/yum_cron/manifests/init.pp", 51]:["/etc/puppetlabs/code/environments/production/site/profiles/manifests/base.pp", 7]
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
```

``validate_legacy`` should be used instead.

**Comment by treydock** [comment]
All validation now handled by native data types.
